export const COMPETITIONS = [
    { code: "WC", name: "World Cup" },
    { code: "PL", name: "Premier League" },
    { code: "CL", name: "Champions League" },
    { code: "EL", name: "Europa League" },
    { code: "ECL", name: "Europa Conference League" },
    { code: "BL", name: "Bundesliga" },
    { code: "LaLiga", name: "La Liga" },
    { code: "SerieA", name: "Serie A" },
    { code: "Ligue1", name: "Ligue 1" },
    { code: "Eredivisie", name: "Eredivisie" },
    { code: "PrimeiraLiga", name: "Primeira Liga" },
    { code: "Championship", name: "Championship" },
    { code: "LeagueOne", name: "League One" },
    { code: "LeagueTwo", name: "League Two" },
    { code: "FACup", name: "FA Cup" },
    { code: "LeagueCup", name: "League Cup" },
]